#!/bin/sh
# Re-theme a generated archify diagram with the product's own design system.
#
# WHY THIS EXISTS
#
# archify owns its palette inside its renderer template: the spec schema has no
# colour field, there is no `--theme` flag, and the presets (classic,
# signal-flow, blueprint, editorial) change geometry and typography, never the
# colours. A regenerated diagram therefore always comes back in archify's own
# navy/cyan (#020617 / #22d3ee), which is NOT the palette the site uses - the
# page would ship one product's colours around a picture drawn in another's.
#
# Editing the template is not an option worth taking: it is a shared skill
# asset, it is 15k lines, and a local edit would be silently reverted (or worse,
# diverge) the next time the skill updates. Editing the generated HTML by hand
# is no better - the next render throws it away.
#
# So this APPENDS an override after the template's own variables. Cascade does
# the rest: archify's block stays byte-intact and still owns every value it
# defines, and anything it adds later that this script does not override keeps
# working. Only the DARK palette is overridden, because the site is dark-only
# and that is the mode the viewer opens in; the light theme is left alone rather
# than half-translated.
#
# The colours below are the tokens from site/index.html, which are in turn the
# tokens the running web interface uses (web/src/index.css). Keep them in sync
# with that file, not with a memory of it.
#
# Usage: scripts/apply-archify-theme.sh <diagram.html>
# Exit codes: 0 themed (or already themed) · 1 the input is not a shaped HTML doc
set -eu

html="${1:-}"
if [ -z "$html" ]; then
  echo "usage: $0 <diagram.html>" >&2
  exit 1
fi
if [ ! -f "$html" ]; then
  printf 'error: %s does not exist\n' "$html" >&2
  exit 1
fi

# Idempotent: a diagram that is already themed is a success, not a second block.
if grep -q 'motita-design-system' "$html"; then
  printf '%s is already themed\n' "$html"
  exit 0
fi

if ! grep -q '</head>' "$html"; then
  printf 'error: %s has no </head> to inject into\n' "$html" >&2
  exit 1
fi

# The cat mark, in the product's blue instead of the green the site used before
# the palette moved. archify does not emit a favicon at all, so this is added
# rather than overridden, and it is the same drawing as site/index.html's.
FAVICON='<link rel="icon" href="data:image/svg+xml,<svg xmlns='"'"'http://www.w3.org/2000/svg'"'"' viewBox='"'"'0 0 32 32'"'"'><g stroke='"'"'%234cc2ff'"'"' stroke-width='"'"'2'"'"' fill='"'"'none'"'"' stroke-linecap='"'"'round'"'"' stroke-linejoin='"'"'round'"'"'><path d='"'"'M8 24 Q4 18 6 12 L4 6 L12 11 Q16 8 20 11 L28 6 L26 12 Q28 18 24 24 Z'"'"'/><circle cx='"'"'13'"'"' cy='"'"'16'"'"' r='"'"'1.5'"'"' fill='"'"'%234cc2ff'"'"' stroke='"'"'none'"'"'/><circle cx='"'"'21'"'"' cy='"'"'16'"'"' r='"'"'1.5'"'"' fill='"'"'%234cc2ff'"'"' stroke='"'"'none'"'"'/><path d='"'"'M16 20 L18 22 L20 20'"'"'/><path d='"'"'M24 24 Q28 22 30 18'"'"'/></g></svg>">'
if ! grep -q 'rel="icon"' "$html"; then
  awk -v fav="$FAVICON" '/<\/head>/ && !done { print fav; done = 1 } { print }' "$html" > "$html.icon"
  mv "$html.icon" "$html"
fi

# --sans / --mono are the faces the site self-hosts. The diagram is an <iframe>
# under the same origin, so it inherits nothing: without this the SVG would fall
# back to system-ui inside a page that is otherwise Sansation.
cat > "$html.tokens" <<'CSS'
<style>
  /* motita-design-system — the site's tokens, applied over archify's own.
     Generated by scripts/apply-archify-theme.sh; do not edit by hand.

     Scoped to [data-theme="dark"] ONLY, never :root. archify's own light block
     is [data-theme="light"], which has the SAME specificity as :root - so a
     :root override here would win on source order and silently repaint the
     light theme dark, turning the Light/Dark toggle into a no-op. The dark
     selector below matches exactly one of the two modes and leaves the other
     theme coherent, which matters because the toggle stays in the toolbar. */
  [data-theme="dark"] {
    --bg: #0a0a0f;
    --grid: rgba(255, 255, 255, 0.05);
    --text: #e8e8ea;
    --text-muted: #9a9aaa;
    --text-dim: #6a6a7a;
    --text-faint: #9a9aaa;

    --panel: rgba(10, 10, 16, 0.78);
    --panel-border: rgba(255, 255, 255, 0.10);
    --lane-fill: rgba(10, 10, 16, 0.35);
    --lane-stroke: rgba(255, 255, 255, 0.14);

    --arrow: #6a6a7a;
    --arrow-emphasis: #4cc2ff;
    --mask: #0a0a0f;

    /* One accent per node kind, all drawn from the site's palette rather than
       archify's defaults: the semantic type still explains what a node does,
       only the hue changes. */
    --frontend-fill:    rgba(109, 213, 255, 0.14);
    --frontend-stroke:  #6dd5ff;
    --backend-fill:     rgba(76, 194, 255, 0.14);
    --backend-stroke:   #4cc2ff;
    --database-fill:    rgba(160, 160, 240, 0.16);
    --database-stroke:  #a0a0f0;
    --cloud-fill:       rgba(240, 160, 64, 0.14);
    --cloud-stroke:     #f0a040;
    --security-fill:    rgba(255, 107, 107, 0.14);
    --security-stroke:  #ff6b6b;
    --messagebus-fill:  rgba(240, 160, 64, 0.13);
    --messagebus-stroke:#f0a040;
    --external-fill:    rgba(255, 255, 255, 0.06);
    --external-stroke:  #9a9aaa;

    --toolbar-bg:       rgba(10, 10, 16, 0.80);
    --toolbar-border:   rgba(255, 255, 255, 0.10);
    --toolbar-text:     #e8e8ea;
    --toolbar-hover:    rgba(10, 10, 16, 0.95);
    --toolbar-menu-bg:  #16161e;
  }

  /* No font override. archify declares `font-family: 'JetBrains Mono'` as a
     LITERAL throughout (there is no --sans/--mono variable to set) and bundles
     its own subset of that face, which is the same typeface the app's own
     --mono resolves to. A variable named --sans here would be inert: measured,
     the viewer reports no Sansation face loaded and every node draws in
     JetBrains Mono. Declaring it would be dead config claiming work it does
     not do. */
</style>
CSS

# Insert before </head>. awk rather than sed: the replacement is a BLOCK, and the
# portable one-liner for that is how you end up needing `r` files and escaping.
awk '
  /<\/head>/ && !done { while ((getline line < tokfile) > 0) print line; done = 1 }
  { print }
' tokfile="$html.tokens" "$html" > "$html.themed"

mv "$html.themed" "$html"
rm -f "$html.tokens"

if ! grep -q 'motita-design-system' "$html"; then
  printf 'error: the override did not land in %s\n' "$html" >&2
  exit 1
fi

printf 'themed %s with the site design system\n' "$html"
